FROM rust:1.93.1-bookworm

RUN rustup component add clippy rustfmt && \
    rustup target add aarch64-unknown-linux-gnu x86_64-pc-windows-gnu

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc-aarch64-linux-gnu libc6-dev-arm64-cross \
    mingw-w64 && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN cargo install cargo-audit cargo-deny
